on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: linuxserver/ffmpeg
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test examples
        run: apt-get update && apt-get install -y bc && cd test-suite && ./run-tests.sh > logout
      - name: Publish results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-suite-results
          path: test-suite/*out*
